name: labeled_list
description: >-
  An implementation of list that accepts an optional
  label with every element added to the list.
version: 0.1.0
homepage: https://github.com/james-alex/labeled_list

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  list_utilities: ^1.0.1
  unique_list: ^1.0.1

dev_dependencies:
  collection: ^1.15.0
  test: ^1.16.8
  pedantic: ^1.11.0
